'use client';
import {useLayoutEffect,useRef,useState,type FormEvent} from 'react';
import Image from 'next/image';
import {Button,Card,Field,Select} from '@mpfrontend-tiffin/dls-adapter';
import type {Locale} from '@mpfrontend/i18n';
import type {Mode} from '@mpfrontend/tokens';
import type {CatalogPage} from '../../api/server/catalog';
import {parseRead,type ReadModels} from '../catalog/model/generated/read-models.gen';
import {business,readBusiness,readMenu,useSession} from '../session/client';
import {Chrome} from '../session/chrome';
import {DiscoverHero} from './discover-hero';
import {DetailRegion,rememberDetailOpener} from '../session/detail-region';
import {feedbackText,type LocalizedFeedback} from '../session/feedback';
import {realtimeLabel} from '../session/realtime-label';
import {orderLabel} from './labels';
import {menuItemPicture,restaurantPicture} from './artwork';
import {useRealtime} from '@mpfrontend/realtime-core/react';
type Menu=ReadModels['menu'];
type Order=ReadModels['order'];
type OrderPage=ReadModels['orders'];
type NotificationPage=ReadModels['notifications'];
type Tracking=ReadModels['tracking'];
export function Delivery({initial,initialLocale,initialMode}:{initial:CatalogPage|undefined;initialLocale:Locale;initialMode:Mode}){
  const [language,setLanguage]=useState(initialLocale),[mode,setMode]=useState(initialMode),[tab,setTab]=useState('restaurants'),[catalog,setCatalog]=useState(initial),[city,setCity]=useState('seattle'),[menu,setMenu]=useState<Menu|null>(null),[quantities,setQuantities]=useState<Record<string,number>>({}),[orders,setOrders]=useState<OrderPage|null>(null),[detail,setDetail]=useState<Order|null>(null),[notifications,setNotifications]=useState<NotificationPage|null>(null),[tracking,setTracking]=useState<Tracking|null>(null),[errorState,setErrorState]=useState<LocalizedFeedback|null>(null),[noticeState,setNoticeState]=useState<LocalizedFeedback|null>(null),[busy,setBusy]=useState(false);
  const error=feedbackText(errorState,language),notice=feedbackText(noticeState,language);
  const setError=(text:string)=>setErrorState(text?{language,text}:null),setNotice=(text:string)=>setNoticeState(text?{language,text}:null);
  const {session,ready,refresh}=useSession();const ar=language==='ar',t=(en:string,arabic:string)=>ar?arabic:en;const customer=session?.roles.includes('customer')===true;
  const attempt=useRef<{fingerprint:string;key:string}|null>(null);
  const money=(value:number,currency='USD')=>new Intl.NumberFormat(language,{style:'currency',currency,currencyDisplay:'code'}).format(value);
  const total=menu?.items.reduce((sum,item)=>sum+item.price*(quantities[item.code]??0),0)??0;
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e instanceof Error?e.message:t('Request failed.','تعذر إتمام الطلب.'));}finally{setBusy(false);}}
  const authorityKey=session?JSON.stringify([session.subject,session.tenant,[...session.roles].sort()]):null;
  const catalogGeneration=useRef(0);
  async function restaurants(page=1,selectedCity=city){const generation=++catalogGeneration.current;const response=await fetch('/api/catalog?'+new URLSearchParams({search:selectedCity,page:String(page),size:'12'}),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(t('Restaurants unavailable.','المطاعم غير متاحة.'));const next=parseRead('catalog',await response.json());if(generation===catalogGeneration.current)setCatalog(next);}
  async function openMenu(id:string){const generation=catalogGeneration.current;const next=await readMenu(id,city,session,language);if(generation!==catalogGeneration.current)return;setMenu(next);setQuantities({});}
  async function loadOrders(page=1){setOrders(await readBusiness('orders','orders?page='+page+'&size=10',session,language));}
  async function loadNotifications(page=1){setNotifications(await readBusiness('notifications','notifications/?page='+page+'&size=10',session,language));}
  const live=useRealtime({session,onUnavailable:fault=>console.warn('MPFRONTEND_REALTIME_UNAVAILABLE',fault.phase,fault.status??'network'),onRevoked:()=>{void refresh(true);},resources:customer?['orders','notifications',...(detail&&['OutForDelivery','Delivered'].includes(detail.status)?['tracking:'+detail.orderId]:[])]:[],onSnapshot:async(resources,signal)=>{
    const nextOrders=resources.includes('orders')?await readBusiness('orders','orders?page='+(orders?.number??1)+'&size=10',session,language,signal):undefined;
    const nextNotifications=resources.includes('notifications')?await readBusiness('notifications','notifications/?page='+(notifications?.number??1)+'&size=10',session,language,signal):undefined;
    const nextDetail=detail&&resources.includes('orders')?await readBusiness('order','orders/'+detail.orderId,session,language,signal):undefined;
    const nextTracking=detail&&resources.includes('tracking:'+detail.orderId)?await readBusiness('tracking','tracking/deliveries/'+detail.orderId,session,language,signal):undefined;
    signal.throwIfAborted();if(!busy){if(nextOrders)setOrders(nextOrders);if(nextNotifications)setNotifications(nextNotifications);if(nextDetail)setDetail(nextDetail);if(nextTracking)setTracking(nextTracking);}
    else setNotice(t('Updates available. Refresh after your current action.','توجد تحديثات. حدّث البيانات بعد انتهاء العملية الحالية.'));
  }});
  async function order(id:string){setDetail(await readBusiness('order','orders/'+id,session,language));setTracking(null);}
  useLayoutEffect(()=>{catalogGeneration.current++;attempt.current=null;setMenu(null);setQuantities({});setOrders(null);setDetail(null);setNotifications(null);setTracking(null);setError('');setNotice('');setTab('restaurants');if(customer&&session?.tenant){setCity(session.tenant);void restaurants(1,session.tenant).catch(()=>undefined);}},[authorityKey]);
  async function select(next:string){setTab(next);if(next==='orders')await loadOrders();if(next==='notifications')await loadNotifications();}
  async function place(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!menu)return;const form=new FormData(event.currentTarget),lines=menu.items.filter(item=>(quantities[item.code]??0)>0).map(item=>({code:item.code,quantity:quantities[item.code]!}));
    const payload={restaurantId:menu.restaurantId,lines,expectedTotal:total,paymentToken:String(form.get('payment')),deliverTo:{recipient:String(form.get('recipient')),phone:String(form.get('phone')),district:String(form.get('district')),line:String(form.get('address'))}};
    const fingerprint=JSON.stringify(payload);if(attempt.current?.fingerprint!==fingerprint)attempt.current={fingerprint,key:crypto.randomUUID()};const key=attempt.current.key;
    await run(async()=>{const accepted=await business<{orderId:string}>('orders',session,language,'POST',payload,key);attempt.current=null;setMenu(null);setQuantities({});setTab('orders');setNotice(t('Order received. Payment and restaurant confirmation will follow.','تم استلام الطلب. ننتظر تأكيد الدفع والمطعم.'));await loadOrders();await order(accepted.orderId);});
  }
  return <main className="reference-shell" onClickCapture={busy?undefined:rememberDetailOpener}><Chrome language={language} setLanguage={setLanguage} mode={mode} setMode={setMode} session={session} ready={ready} city={city}><a className="tiffin-wordmark" href="/" aria-label={t('Tiffin home','الصفحة الرئيسية لتيفين')}><span className="tiffin-mark" aria-hidden="true">T</span><strong>Tiffin</strong></a><span className="app-primary-links"><Button tone="secondary" aria-current={tab==='restaurants'?'page':undefined} onClick={()=>void run(()=>select('restaurants'))}>{t('Restaurants','المطاعم')}</Button>{customer&&<><Button tone="secondary" aria-current={tab==='orders'?'page':undefined} onClick={()=>void run(()=>select('orders'))}>{t('My orders','طلباتي')}</Button><Button tone="secondary" aria-current={tab==='notifications'?'page':undefined} onClick={()=>void run(()=>select('notifications'))}>{t('Notifications','الإشعارات')}</Button></>}</span></Chrome>{tab==='restaurants'?<DiscoverHero arabic={ar}/>:<div><p className="reference-eyebrow">{t('Your Tiffin','طلباتك في تيفين')}</p><h1 className="app-title">{t(tab==='orders'?'Your orders':'Your notifications',tab==='orders'?'طلباتك':'إشعاراتك')}</h1></div>}
    {customer&&<p className="app-muted" role="status">{t('Live updates','التحديثات المباشرة')}: {realtimeLabel(live,ar)}</p>}
    {error&&<p role="alert" className="reference-alert">{error}</p>}{notice&&<p role="status" className="app-success">{notice}</p>}
    {session&&!customer&&<Card><p>{t('Use the operations app for your restaurant, courier or administration account.','استخدم لوحة العمليات لحساب المطعم أو التوصيل أو الإدارة.')}</p><a href="http://localhost:4412">{t('Open operations','فتح لوحة العمليات')}</a></Card>}
    {tab==='restaurants'&&<><div id="catalog-start" className="catalog-heading"><div><p className="reference-eyebrow">{t('Explore nearby','اكتشف المطاعم القريبة')}</p><h2>{t('Restaurants in your city','مطاعم في مدينتك')}</h2></div>{catalog&&<span className="app-muted">{catalog.items.length} {t('shown on this page','مطعماً في هذه الصفحة')}</span>}</div><Card><form className="app-form catalog-filters" onSubmit={event=>{event.preventDefault();setMenu(null);void run(()=>restaurants());}}><Select label={t('City','المدينة')} value={city} disabled={!!session} onChange={e=>setCity(e.target.value)}><option value="seattle">Seattle</option><option value="austin">Austin</option></Select><Button type="submit" loading={busy}>{t('Find restaurants','عرض المطاعم')}</Button></form></Card>
    <div className="app-grid">{catalog?.items.map(raw=>{const restaurant=raw,picture=restaurantPicture(restaurant.name,restaurant.pictureId,customer);return <Card key={restaurant.restaurantId}><article className="app-product">{picture&&<Image className="app-product-picture" unoptimized src={picture} width={720} height={440} alt={restaurant.name}/>}<span className="app-badge">{restaurant.isOpen?t('Open now','مفتوح الآن'):t('Closed','مغلق')}</span><h2>{restaurant.name}</h2><p className="app-muted">{restaurant.city}</p><Button tone="secondary" disabled={busy} onClick={()=>void run(()=>openMenu(restaurant.restaurantId))}>{t('View menu','عرض القائمة')}</Button></article></Card>;})}</div>{catalog?.items.length===0&&<p>{t('No restaurants found in this city.','لا توجد مطاعم في هذه المدينة.')}</p>}{!catalog&&<p>{t('Restaurants are unavailable. Try again.','المطاعم غير متاحة. حاول مرة أخرى.')}</p>}
    {catalog&&<div className="app-pagination"><Button disabled={busy||catalog.number<=1} onClick={()=>void run(()=>restaurants(catalog.number-1))}>{t('Previous','السابق')}</Button><span>{catalog.number}</span><Button disabled={busy||!catalog.hasMore} onClick={()=>void run(()=>restaurants(catalog.number+1))}>{t('Next','التالي')}</Button></div>}
    {menu&&<DetailRegion identity={menu.restaurantId} label={menu.name}><div className="app-actions"><h2>{menu.name}</h2><Button tone="secondary" disabled={busy} onClick={()=>{setMenu(null);setQuantities({});}}>{t('Close menu','إغلاق القائمة')}</Button></div><ul className="app-list">{menu.items.map(item=>{const picture=menuItemPicture(item.code,item.pictureId,customer);return <li key={item.code} className="app-row app-menu-row"><div className="app-menu-leading">{picture&&<Image className="app-menu-picture" unoptimized src={picture} width={320} height={240} alt={item.name}/>}<div><strong>{item.name}</strong><p>{money(item.price,menu.currency)} · {item.isAvailable?t('Available','متاح'):t('Sold out','غير متاح')}</p></div></div><Field label={t('Quantity','الكمية')+' · '+item.name} type="number" min="0" max="10" value={quantities[item.code]??0} disabled={!item.isAvailable||!menu.isOpen||!customer||busy} onChange={e=>{const value=Number(e.target.value);if(Number.isInteger(value)&&value>=0&&value<=10)setQuantities(current=>({...current,[item.code]:value}));}}/></li>;})}</ul><h3>{t('Estimated total','المجموع المتوقع')}: {money(total,menu.currency)}</h3><p className="app-muted">{t('The restaurant confirms current prices when you place the order.','يؤكد المطعم الأسعار الحالية عند إرسال الطلب.')}</p>{!customer?<a href="/api/session/login">{t('Sign in to order','سجل الدخول لطلب الطعام')}</a>:<form className="app-form" onSubmit={e=>void place(e)}><Field label={t('Recipient','المستلم')} name="recipient" required maxLength={100} defaultValue={session!.name}/><Field label={t('Phone','الهاتف')} name="phone" type="tel" inputMode="tel" required maxLength={30} placeholder="206-555-0142" helper={t('Any non-empty test number is accepted.','يُقبل أي رقم تجريبي غير فارغ.')}/><Field label={t('District','الحي')} name="district" required maxLength={60}/><Field label={t('Address','العنوان')} name="address" required maxLength={300}/><Select label={t('Demo payment method','وسيلة دفع تجريبية')} name="payment"><option value="tok_ok">{t('Demo card — approved','بطاقة تجريبية — مقبولة')}</option><option value="tok_insufficient_funds">{t('Demo card — declined','بطاقة تجريبية — مرفوضة')}</option></Select><Button type="submit" loading={busy} disabled={!menu.isOpen||total<=0}>{t('Place order','إرسال الطلب')}</Button></form>}</DetailRegion>}</>}
    {tab==='orders'&&customer&&<><Card><div className="app-actions"><h2>{t('Order history','سجل الطلبات')}</h2><Button tone="secondary" loading={busy} onClick={()=>void run(async()=>{await loadOrders(orders?.number??1);if(detail)await order(detail.orderId);})}>{t('Refresh','تحديث')}</Button></div><ul className="app-list">{orders?.items.map(item=><li className="app-row" key={item.orderId}><div><strong>{item.orderNumber} · {item.restaurantName}</strong><p>{orderLabel(item.status,ar)} · {money(item.total,item.currency)}</p></div><Button tone="secondary" onClick={()=>void run(()=>order(item.orderId))}>{t('View order','عرض الطلب')}</Button></li>)}</ul>{orders?.items.length===0&&<p>{t('No orders yet.','لا توجد طلبات بعد.')}</p>}{orders&&<div className="app-pagination"><Button disabled={busy||orders.number<=1} onClick={()=>void run(()=>loadOrders(orders.number-1))}>{t('Previous','السابق')}</Button><Button disabled={busy||!orders.hasMore} onClick={()=>void run(()=>loadOrders(orders.number+1))}>{t('Next','التالي')}</Button></div>}</Card>
      {detail&&<DetailRegion identity={detail.orderId} label={detail.orderNumber}><h2>{detail.orderNumber}</h2><p className="app-badge">{orderLabel(detail.status,ar)}</p><p>{detail.restaurantName} · {money(detail.total,detail.currency)}</p>{detail.cancellationReason&&<p>{detail.cancellationReason}</p>}{detail.refunded&&<p>{t('Payment refunded.','تم استرداد المبلغ.')}</p>}<ul>{detail.lines?.map(line=><li key={line.code}>{line.name} × {line.quantity}</li>)}</ul><ol className="app-timeline">{detail.history?.map((entry,i)=><li key={i}>{orderLabel(entry.status,ar)} · {new Date(entry.occurredOnUtc).toLocaleString(language)}{entry.note&&' · '+entry.note}</li>)}</ol>{detail.courierName&&<p>{t('Courier','المندوب')}: {detail.courierName}</p>}{detail.readyInMinutes&&<p>{t('Ready in minutes','مدة التحضير بالدقائق')}: {detail.readyInMinutes}</p>}{['Placed','Paid'].includes(detail.status)&&<Button disabled={busy} onClick={()=>void run(async()=>{setDetail(await business<Order>('orders/'+detail.orderId+'/cancel',session,language,'POST'));await loadOrders();})}>{t('Cancel order','إلغاء الطلب')}</Button>}{['OutForDelivery','Delivered'].includes(detail.status)&&<Button tone="secondary" disabled={busy} onClick={()=>void run(async()=>setTracking(await readBusiness('tracking','tracking/deliveries/'+detail.orderId,session,language)))}>{t('Track delivery','تتبع التوصيل')}</Button>}{tracking&&<div className="app-detail"><h3>{t('Delivery location','موقع التوصيل')}</h3>{tracking.lastSeen?<><p>{tracking.lastSeen.latitude}, {tracking.lastSeen.longitude}</p><p>{new Date(tracking.lastSeen.recordedOnUtc).toLocaleString(language)}</p></>:<p>{t('Waiting for the first courier position.','ننتظر موقع المندوب.')}</p>}</div>}</DetailRegion>}</>}
    {tab==='notifications'&&customer&&<Card><div className="app-actions"><h2>{t('Notifications','الإشعارات')}</h2><Button onClick={()=>void run(()=>loadNotifications(notifications?.number??1))}>{t('Refresh','تحديث')}</Button></div><ul className="app-list">{notifications?.items.map(item=><li key={item.notificationId} className="app-row"><div><p>{item.text}</p><small>{new Date(item.occurredOnUtc).toLocaleString(language)}</small></div>{!item.readOnUtc&&<Button tone="secondary" disabled={busy} onClick={()=>void run(async()=>{await business('notifications/'+item.notificationId+'/read',session,language,'POST');await loadNotifications(notifications?.number??1);})}>{t('Mark read','تمت القراءة')}</Button>}<Button tone="secondary" onClick={()=>void run(async()=>{setTab('orders');await loadOrders();await order(item.orderId);})}>{t('View order','عرض الطلب')}</Button></li>)}</ul>{notifications?.items.length===0&&<p>{t('No notifications yet.','لا توجد إشعارات بعد.')}</p>}{notifications&&<div className="app-pagination"><Button disabled={busy||notifications.number<=1} onClick={()=>void run(()=>loadNotifications(notifications.number-1))}>{t('Previous','السابق')}</Button><Button disabled={busy||!notifications.hasMore} onClick={()=>void run(()=>loadNotifications(notifications.number+1))}>{t('Next','التالي')}</Button></div>}</Card>}
  </main>;
}
