'use client';
import {useLayoutEffect,useRef,useState,type FormEvent} from 'react';
import Image from 'next/image';
import {Button,Card,Field,Select,ResourceTable} from '@mpfrontend-tiffin/dls-adapter';
import type {Locale} from '@mpfrontend/i18n';
import type {Mode} from '@mpfrontend/tokens';
import {business,captureSessionOperation,readBusiness,readMenu,BusinessError,useSession} from '../session/client';
import {parseRead,type ReadModels} from '../catalog/model/generated/read-models.gen';
import {Chrome} from '../session/chrome';
import {useRealtime} from '@mpfrontend/realtime-core/react';
import {realtimeLabel} from '../session/realtime-label';
import {tableLabels,presentRow} from './table-presentation';
import {feedbackText,type LocalizedFeedback} from './feedback';
import {AcceptTicketForm} from './request-form';
import {uploadMediaObject} from './media-upload';
type Row=Record<string,unknown>;type Page=ReadModels['catalog'|'kitchen'];
type Menu=ReadModels['menu'];
function Table({rows,keys,caption,language}:{rows:Row[];keys:string[];caption:string;language:Locale}){return <ResourceTable fields={keys.map(key=>({key,type:'string' as const,required:false,nullable:true,editable:false}))} rows={rows.map(row=>presentRow(row,keys,language))} caption={caption} labels={tableLabels(language)} format={value=>String(value??'—')}/>;}
export function Dashboard({initialLocale,initialMode}:{initialLocale:Locale;initialMode:Mode}){
  const [language,setLanguage]=useState(initialLocale),[mode,setMode]=useState(initialMode),[tab,setTab]=useState(''),[rows,setRows]=useState<Row[]>([]),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false),[menu,setMenu]=useState<Menu|null>(null),[selected,setSelected]=useState<Row|null>(null),[busy,setBusy]=useState(false),[errorState,setErrorState]=useState<LocalizedFeedback|null>(null),[noticeState,setNoticeState]=useState<LocalizedFeedback|null>(null),[courier,setCourier]=useState<Row|null>(null),[filter,setFilter]=useState('Pending');
  const error=feedbackText(errorState,language),notice=feedbackText(noticeState,language);
  const setError=(text:string)=>setErrorState(text?{language,text}:null),setNotice=(text:string)=>setNoticeState(text?{language,text}:null);
  const queryEpoch=useRef(0);
  const {session,ready,refresh}=useSession();const ar=language==='ar',t=(en:string,arabic:string)=>ar?arabic:en;
  const manager=session?.roles.includes('restaurant-manager'),isCourier=session?.roles.includes('courier');
  const [updates,setUpdates]=useState(false);
  const live=useRealtime({session,onUnavailable:fault=>console.warn('MPFRONTEND_REALTIME_UNAVAILABLE',fault.phase,fault.status??'network'),onRevoked:()=>{void refresh(true);},resources:manager?['kitchen']:isCourier?['courier']:[],onInvalidate:()=>setUpdates(true),onSnapshot:async(resources,signal)=>{
    for(const resource of resources){
      try{if(resource==='kitchen')await readBusiness('kitchen','kitchen/tickets/?status=Pending&page=1&size=20',session,language,signal);else await business('courier/delivery',session,language,'GET',undefined,undefined,signal);}
      catch(error){if(!(resource==='courier'&&error instanceof BusinessError&&error.status===404))throw error;}
    }
    signal.throwIfAborted();setUpdates(true); // A recovered subscription must never overwrite an active draft.
  }});
  const modules=[...(manager?['restaurants','kitchen']:[]),...(isCourier?['courier']:[])];
  const titles:Record<string,string>={restaurants:t('Restaurants & menus','المطاعم والقوائم'),kitchen:t('Kitchen orders','طلبات المطبخ'),courier:t('Courier workspace','لوحة المندوب')};
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:t('Request failed.','تعذر تنفيذ الطلب.'));}finally{setBusy(false);}}
  async function load(next=tab,number=1){const epoch=++queryEpoch.current;const assertCurrent=()=>{if(epoch!==queryEpoch.current)throw new DOMException('QUERY_CHANGED','AbortError');};setPage(number);setSelected(null);setRows([]);setHasMore(false);setCourier(null);const query=new URLSearchParams({page:String(number),size:'20'});let result:Page;
    if(next==='restaurants'){query.set('search',session?.tenant??'seattle');const response=await fetch('/api/catalog?'+query,{cache:'no-store'});if(!response.ok)throw new Error(t('Restaurants unavailable.','المطاعم غير متاحة.'));result=parseRead('catalog',await response.json());}
    else if(next==='kitchen'){if(filter)query.set('status',filter);result=await readBusiness('kitchen','kitchen/tickets/?'+query,session,language);}
    else if(next==='courier'){try{const delivery=await business<Row>('courier/delivery',session,language);assertCurrent();setCourier(delivery);}catch(e){if(e instanceof BusinessError&&e.status===404){assertCurrent();setCourier(null);setNotice(t('No active delivery. Go on duty to receive assignments.','لا توجد مهمة توصيل. ابدأ العمل لاستقبال الطلبات.'));}else throw e;}return;}
    else throw new Error('UNKNOWN_READ_RESOURCE');
    assertCurrent();setRows(result.items);setHasMore(result.hasMore);
  }
  const authority=JSON.stringify([session?.subject,session?.tenant,[...(session?.roles??[])].sort()]);
  useLayoutEffect(()=>{queryEpoch.current++;setRows([]);setMenu(null);setSelected(null);setCourier(null);setTab('');setUpdates(false);setError('');setNotice('');},[authority]);
  async function choose(next:string){setTab(next);setMenu(null);await load(next);}
  async function openMenu(id:string){setMenu(await readMenu(id,session?.tenant??'seattle',session,language));}
  async function submit(event:FormEvent<HTMLFormElement>,action:(form:FormData)=>Promise<void>){event.preventDefault();const data=new FormData(event.currentTarget);await run(()=>action(data));}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const file=new FormData(event.currentTarget).get('picture');if(!(file instanceof File)||!menu)return;const current=menu;
    await run(async()=>{const scope=captureSessionOperation(session);const ticket=await business<ReadModels['reserve-media-upload']>('media/uploads',session,language,'POST',{purpose:'restaurant-picture',fileName:file.name,contentType:file.type,size:file.size});await uploadMediaObject(ticket,file,{allowedOrigin:process.env.NEXT_PUBLIC_MEDIA_ORIGIN??'http://localhost:39000',signal:scope.signal});scope.assertCurrent();await business<ReadModels['confirm-media-upload']>('media/'+ticket.mediaId+'/confirm',session,language,'POST');setMenu(await business<Menu>('restaurants/'+current.restaurantId+'/picture',session,language,'PUT',{pictureId:ticket.mediaId}));setNotice(t('Restaurant picture saved.','تم حفظ صورة المطعم.'));});
  }
  return <main className="reference-shell operations-shell"><Chrome language={language} setLanguage={setLanguage} mode={mode} setMode={setMode} session={session} ready={ready}><a className="tiffin-wordmark" href="/" aria-label={t('Tiffin Operations home','الصفحة الرئيسية لعمليات تيفين')}><span className="tiffin-mark" aria-hidden="true">T</span><strong>Tiffin</strong></a><span className="operations-product-label">{t('Operations','العمليات')}</span></Chrome><header className={'operations-heading'+(!session?' operations-heading--guest':'')}><div className="operations-heading-copy"><p className="reference-eyebrow">{t(session?'Tiffin workspace':'Built for delivery teams',session?'مساحة عمل تيفين':'مصمم لفرق التوصيل')}</p><h1>{t(session?'Delivery operations':'Run every delivery from one workspace.',session?'إدارة عمليات التوصيل':'أدِر كل عملية توصيل من مساحة عمل واحدة.')}</h1><p>{t(session?'Coordinate restaurants, kitchen orders and your delivery team.':'Keep restaurants, kitchen decisions and couriers moving together—from the first order to the final handoff.',session?'نسّق المطاعم وطلبات المطبخ وفريق التوصيل.':'اجمع المطاعم وقرارات المطبخ والمندوبين في مسار واحد من الطلب حتى التسليم.')}</p>{session?.tenant&&<div className="operations-context"><span className="app-badge">{session.tenant}</span>{session.roles.map(role=><span className="app-badge" key={role}>{role}</span>)}</div>}{ready&&!session&&<div className="operations-hero-actions"><a className="operations-signin" href="/api/session/login">{t('Open operations','فتح لوحة العمليات')}</a><span>{t('Secure, role-aware access with Tiffin identity.','دخول آمن ومقيد بالدور عبر هوية تيفين.')}</span></div>}</div>{ready&&!session&&<div className="operations-role-grid" aria-label={t('Operations capabilities','قدرات لوحة العمليات')}><article><span>01</span><h2>{t('Restaurant control','إدارة المطعم')}</h2><p>{t('Keep storefront status, menus and imagery current.','حدّث حالة المطعم والقوائم والصور.')}</p></article><article><span>02</span><h2>{t('Kitchen flow','مسار المطبخ')}</h2><p>{t('Review incoming tickets and make timely decisions.','راجع الطلبات الجديدة واتخذ القرار في الوقت المناسب.')}</p></article><article><span>03</span><h2>{t('Courier dispatch','إدارة المندوب')}</h2><p>{t('Manage duty, assignments, position and completion.','أدِر الدوام والمهمات والموقع وإتمام التوصيل.')}</p></article><article><span>04</span><h2>{t('Role-aware access','وصول مبني على الدور')}</h2><p>{t('Each team member sees only the tools assigned in Keycloak.','يرى كل عضو فقط الأدوات الممنوحة له في كيكلاك.')}</p></article></div>}</header>
    {(manager||isCourier)&&<p className="app-muted" role="status">{t('Live updates','التحديثات المباشرة')}: {realtimeLabel(live,ar)}{updates&&' · '+t('Updates available. Refresh when your edits are safe.','توجد تحديثات. حدّث البيانات بعد حفظ تعديلاتك.')}</p>}
    {error&&<p role="alert" className="reference-alert">{error}</p>}{notice&&<p role="status" className="app-success">{notice}</p>}{session&&modules.length===0&&<p>{t('This account has no operations permissions.','لا يملك هذا الحساب صلاحيات العمليات.')}</p>}
    {modules.length>0&&<nav className="operations-navigation" aria-label={t('Operations modules','أقسام العمليات')}>{modules.map(module=><Button key={module} tone="secondary" disabled={busy} aria-current={tab===module?'page':undefined} onClick={()=>void run(()=>choose(module))}>{titles[module]}</Button>)}</nav>}
    <section className="operations-content" aria-label={t('Current workspace','مساحة العمل الحالية')}>{session&&modules.length>0&&!tab&&<Card><h2>{t('Your workspace is ready','مساحة العمل جاهزة')}</h2><p className="app-muted">{t('Choose a module to view live records and available actions.','اختر قسماً لعرض السجلات الحالية والإجراءات المتاحة.')}</p></Card>}
    {tab&&modules.includes(tab)&&<Card><h2>{titles[tab]}</h2><form className="app-form" onSubmit={event=>{event.preventDefault();void run(()=>load());}}>{tab==='kitchen'&&<Select label={t('Ticket status','حالة الطلب')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="Pending">{t('Pending','بانتظار الرد')}</option><option value="">{t('All','الكل')}</option><option value="Accepted">{t('Accepted','مقبول')}</option><option value="Rejected">{t('Rejected','مرفوض')}</option></Select>}<Button loading={busy} type="submit">{t('Refresh','تحديث')}</Button></form>
      {busy?<p className="operations-empty" role="status">{t('Loading records…','جارٍ تحميل السجلات…')}</p>:error?<p className="operations-empty">{t('Could not load records. Retry with Refresh.','تعذر تحميل السجلات. أعد المحاولة بالتحديث.')}</p>:tab!=='courier'&&rows.length===0?<p className="operations-empty">{tab==='kitchen'?t('No kitchen tickets match this status.','لا توجد طلبات مطبخ بهذه الحالة.'):t('No records match these filters.','لا توجد سجلات تطابق هذه الفلاتر.')}</p>:tab==='courier'?<div>{courier&&<><Table language={language} rows={[courier]} keys={'onDuty'in courier?['name','city','onDuty','carryingOrderId']:['orderNumber','status','restaurantName','recipient','phone','district','line']} caption={titles[tab]!}/>{typeof courier.orderId==='string'&&courier.status==='Assigned'&&<Button loading={busy} onClick={()=>void run(async()=>{setCourier(await business<Row>('courier/delivery/complete',session,language,'POST',{orderId:courier.orderId}));setNotice(t('Delivery completed.','تم تسليم الطلب.'));})}>{t('Complete delivery','تأكيد التسليم')}</Button>}</>}<div className="app-actions"><Button disabled={busy} onClick={()=>void run(async()=>setCourier(await business<Row>('courier/duty/on',session,language,'POST',{})))}>{t('Go on duty','بدء العمل')}</Button><Button tone="secondary" disabled={busy} onClick={()=>void run(async()=>setCourier(await business<Row>('courier/duty/off',session,language,'POST',{})))}>{t('Go off duty','إنهاء العمل')}</Button></div></div>:<ul className="app-list">{rows.map((row,i)=><li key={String(row.restaurantId??row.orderId??i)} className="app-row"><div><strong>{String(row.name??row.orderNumber)}</strong><p>{tab==='restaurants'?(row.isOpen?t('Open','مفتوح'):t('Closed','مغلق')):String(row.restaurantName)+' · '+presentRow(row,['status'],language).status}</p></div><Button tone="secondary" disabled={busy} onClick={()=>void run(async()=>{if(tab==='restaurants')await openMenu(String(row.restaurantId));else setSelected(row);})}>{t('Manage','إدارة')}</Button></li>)}</ul>}
      {tab!=='courier'&&<div className="app-pagination"><Button disabled={busy||page<=1} onClick={()=>void run(()=>load(tab,page-1))}>{t('Previous','السابق')}</Button><span>{page}</span><Button disabled={busy||!hasMore} onClick={()=>void run(()=>load(tab,page+1))}>{t('Next','التالي')}</Button></div>}
    </Card>}
    {tab==='restaurants'&&manager&&<><Card><h2>{t('Register restaurant','تسجيل مطعم')}</h2><form className="app-form" onSubmit={event=>void submit(event,async form=>{const value=await business<Menu>('restaurants',session,language,'POST',{name:String(form.get('name')),currency:String(form.get('currency'))});setMenu(value);setNotice(t('Restaurant created. Add a menu before opening.','تم إنشاء المطعم. أضف القائمة قبل فتحه.'));await load('restaurants');})}><Field name="name" label={t('Restaurant name','اسم المطعم')} required/><Select name="currency" label={t('Currency','العملة')}><option>USD</option></Select><Button type="submit" loading={busy}>{t('Register','تسجيل')}</Button></form></Card>
      {menu&&<Card><h2>{menu.name}</h2>{menu.pictureId&&<Image className="operations-restaurant-picture" unoptimized src={'/api/picture/'+menu.pictureId} width={960} height={540} alt={menu.name}/>}<p>{menu.isOpen?t('Open','مفتوح'):t('Closed','مغلق')} · {menu.currency}</p><Button loading={busy} onClick={()=>void run(async()=>setMenu(await business<Menu>('restaurants/'+menu.restaurantId+'/'+(menu.isOpen?'close':'open'),session,language,'POST')))}>{menu.isOpen?t('Close restaurant','إغلاق المطعم'):t('Open restaurant','فتح المطعم')}</Button><div className="operations-menu-gallery">{menu.items.filter(item=>item.pictureId).map(item=><figure key={item.code}><Image unoptimized src={'/api/picture/'+item.pictureId} width={360} height={240} alt={item.name}/><figcaption>{item.name}</figcaption></figure>)}</div><Table language={language} rows={menu.items} keys={['code','name','price','isAvailable','pictureId']} caption={t('Menu','القائمة')}/><form className="app-form" onSubmit={event=>void submit(event,async form=>{const pictureId=String(form.get('pictureId')??'').trim();setMenu(await business<Menu>('restaurants/'+menu.restaurantId+'/menu/'+encodeURIComponent(String(form.get('code'))),session,language,'PUT',{name:String(form.get('name')),price:Number(form.get('price')),isAvailable:form.get('available')==='yes',pictureId:pictureId||null}));setNotice(t('Menu saved.','تم حفظ القائمة.'));})}><Field name="code" label={t('Item code','رمز الصنف')} required/><Field name="name" label={t('Item name','اسم الصنف')} required/><Field name="price" label={t('Price','السعر')} type="number" min="0.01" step="0.01" required/><Field name="pictureId" label={t('Media picture ID (optional)','معرّف صورة الوسائط (اختياري)')}/><Select name="available" label={t('Availability','التوفر')}><option value="yes">{t('Available','متاح')}</option><option value="no">{t('Sold out','غير متاح')}</option></Select><Button type="submit" loading={busy}>{t('Save menu item','حفظ الصنف')}</Button></form><form className="app-form" onSubmit={event=>void upload(event)}><Field name="picture" type="file" accept="image/jpeg,image/png,image/webp" label={t('Restaurant picture','صورة المطعم')} required/><Button type="submit" loading={busy}>{t('Upload picture','رفع الصورة')}</Button></form></Card>}</>}
    {tab==='kitchen'&&selected&&manager&&<Card><h2>{String(selected.orderNumber)}</h2><Table language={language} rows={(selected.lines??[]) as Row[]} keys={['code','name','quantity']} caption={t('Kitchen ticket','طلب المطبخ')}/>{selected.status==='Pending'&&<><AcceptTicketForm key={authority+':'+selected.orderId} ar={ar} disabled={busy} onSubmit={payload=>void run(async()=>{await business<Row>('kitchen/tickets/'+selected.orderId+'/accept',session,language,'POST',payload,crypto.randomUUID());await load('kitchen');setNotice(t('Order accepted.','تم قبول الطلب.'));})}/><form className="app-form" onSubmit={event=>void submit(event,async form=>{await business('kitchen/tickets/'+selected.orderId+'/reject',session,language,'POST',{reason:String(form.get('reason'))});await load('kitchen');setNotice(t('Order rejected.','تم رفض الطلب.'));})}><Field name="reason" label={t('Rejection reason','سبب الرفض')} required/><Button tone="secondary" loading={busy} type="submit">{t('Reject order','رفض الطلب')}</Button></form></>}</Card>}
    {tab==='courier'&&isCourier&&typeof courier?.orderId==='string'&&courier.status==='Assigned'&&<Card><h2>{t('Report delivery position','تحديث موقع التوصيل')}</h2><form className="app-form" onSubmit={event=>void submit(event,async form=>{await business('tracking/deliveries/'+courier.orderId+'/positions',session,language,'POST',{latitude:Number(form.get('latitude')),longitude:Number(form.get('longitude'))});setNotice(t('Position reported.','تم تحديث الموقع.'));})}><Field name="latitude" label={t('Latitude','خط العرض')} type="number" step="any" min="-90" max="90" required/><Field name="longitude" label={t('Longitude','خط الطول')} type="number" step="any" min="-180" max="180" required/><Button type="submit" loading={busy}>{t('Report position','تحديث الموقع')}</Button></form></Card>}
    </section>
  </main>;
}
